### ISSUE TITLE
Difference between model_sample_compare and level_sample_compare for 

### ISSUE THREAD

**Issue by BisonKok** [nanoporetech/tombo#119] opened 2018-10-22 01:53 UTC
Hi Marcus. `sample_compare` option for `tombo detect_modifications` in v1.4 was divided into `model_sample_compare` and `level_sample_compare` in v1.5. Can I know what the difference is between `model_sample_compare` and `level_sample_compare`? Thanks in advance.

**Comment by marcus1487** [comment] 2018-10-22 12:49
duplicate of #120

**Closed by marcus1487** 2018-10-22 12:49 UTC
Labels: duplicate
