### ISSUE TITLE
Question: "No locations identified. Most likely an empty statistics file."

### ISSUE THREAD

**Issue by stelmanAM** [nanoporetech/tombo#228] opened 2020-03-09 18:51 UTC
I ran the following pipeline in tombo 1.5.1+ on CentOS 6.10 with 256GB RAM.

There were two separate sequencing runs. Each was demultiplexed and then fast5 files organized as 2 subdirs of folder "Barcode1" and 2 subdirs of folder "Barcode2".

`tombo resquiggle --dna --processes 16 --num-most-common-errors 3 --overwrite Barcode1 ../dm3.fasta`
`tombo resquiggle --dna --processes 16 --num-most-common-errors 3 --overwrite Barcode2 ../dm3.fasta`

At this point, I checked the max "sequencing depth" and it maxed at approx. 8000 reads, which is too much data to run through `tombo detect_modifications level_sample_compare` without memory problems.

I therefore filtered the data to produce a max depth of approx 50 as follows:

`tombo filter level_coverage --fast5-basedirs Barcode1 --percent-to-filter 25`
`tombo filter level_coverage --fast5-basedirs Barcode2 --percent-to-filter 25`
`tombo text_output browser_files --fast5-basedirs Barcode1 --control-fast5-basedirs Barcode2 --genome-fasta ../dm3.fasta`
`for f in *.bedgraph; do echo $f; awk 'BEGIN {max=0} {if(max<0+$4) max=$4} END{print max}' $f; done`

    tombo_results.coverage.control.minus.bedgraph
    44
    tombo_results.coverage.control.plus.bedgraph
    49
    tombo_results.coverage.sample.minus.bedgraph
    47
    tombo_results.coverage.sample.plus.bedgraph
    43

The subsequent command took 112 hours to process on 8 cores:

`tombo detect_modifications level_sample_compare --fast5-basedirs Barcode2 --alternate-fast5-basedirs Barcode1 --minimum-test-reads 50 --processes 8 --statistics-file-basename level_comp_stats --multiprocess-region-size 25`

Note that both filtering, reducing core # to 8, and reducing multiprocess-region-size to 25 were necessary to get this to run without memory problems.

I then attempted the two following commands, but received the error in the subject line of this post for the first, and empty wig files for the second:
`tombo plot most_significant --fast5-basedirs Barcode2 --control-fast5-basedirs Barcode1 --statistics-filename level_comp_stats.tombo.stats --pdf-filename Barcode1v2_most_significant_plot.pdf`
`tombo text_output browser_files --statistics-filename level_comp_stats.tombo.stats --browser-file-basename level_compare_browserfile --file-types statistic`

I am now stuck trying to understand if I have filtered too much data to get meaningful results, or if there is another solution to get this data to run with 256GB RAM. If throwing more RAM at the problem is required, I can do that, but would prefer not to upgrade if it won't solve the problem.

**Comment by marcus1487** [comment] 2020-03-09 19:18
The issue is likely the `--minimum-test-reads 50` setting. With coverage down-sampled to less than 50X in each sample and a minimum of 50 reads required to produce a result, there are no valid sites remaining. Setting this value to `1` will allow statistics to be computed at all sites, but should be handled appropriately downstream as level comparison at low coverage is quite poor.

It is quite curious that the processing is taking this long. In order to diagnose your issues without spending such high compute costs, could you process a smaller region of the reference ([genome locations filter docs](https://nanoporetech.github.io/tombo/filtering.html#tombo-filter-genome-locations)). Then once the issues have been identified and hopefully resolved a whole reference run could be completed.

For the RAM usage, by what means is the usage being tracked? I have seen job scheduling software (SGE, UGE, SLURM, etc) mis-calculate the RAM usage for tombo due to the reference loaded into a shared memory space.

Multiprocessing region size should not have to be reduced to this level in order to process a sample with this level of coverage. What is the output of the detect_modifications command? And at what stage is the command stalling?

**Comment by stelmanAM** [comment] 2020-03-09 19:30
>With coverage down-sampled...

Ah, thanks, should have caught that.

>In order to diagnose your issues...

I will attempt a single chromosome and see if that helps for debugging purposes.

> For the RAM usage, by what means is the usage being tracked?

We don't use scheduling software. Mostly I use top. However, what I observe regarding the memory issues is the application crashing with things memory allocation errors (details previously reported). I then manually kill zombie tombo processes (if any) before continuing.

>What is the output of the detect_modifications command? And at what stage is the command stalling?

It doesn't necessarily stall, just runs very slow. Here's the final output:

`tombo detect_modifications level_sample_compare --fast5-basedirs Barcode2 --alternate-fast5-basedirs Barcode1 --minimum-test-reads 50 --processes 8 --statistics-file-basename level_comp_stats --multiprocess-region-size 25`
[18:10:49] Parsing Tombo index file(s).
[18:11:10] Performing two-sample group comparison significance testing.
[18:11:10] Parsing Tombo index file(s).
[18:11:35] Calculating read coverage regions.
[18:11:35] Calculating read coverage.
[18:11:42] Calculating read coverage.
[18:16:18] Performing modified base detection across genomic regions.
100%|██████████████████████████████████████████████████████████████████████████████████| 13494359/13494359 [112:19:31<00:00, 33.37it/s]

**Comment by marcus1487** [comment] 2020-03-09 19:37
This may be a disk speed issue. Are the FAST5s being accessed over a network file system? Could they be moved to a location with faster read access (local SSD)? 

For a test set, I would recommend selecting a region smaller (maybe 10k bases) than a whole chromosome for a test run that is very quick. And then scaling up once a successful run has been completed from end-to-end.

I would also suspect that increasing the `--multiprocess-region-size` to a larger value would help potential I/O issues (since each read file would need to be opened fewer times). Obviously the memory issue needs to be resolved for this to work. Could you test the effect of increasing this value on the smaller test set to see if the downsampling has helped resolve this issue (if you have not done so already).

**Comment by stelmanAM** [comment] 2020-03-09 23:44
Interestingly, before doing the recommended tests, I re-ran as before with two adjustments: reducing minimum-test-reads to 1 and increasing multiprocess-region-size to 1000.

Not sure why it ran without any memory issues this time, but it completed in a little over 3 hours this time:

`tombo detect_modifications level_sample_compare --fast5-basedirs Barcode2 --alternate-fast5-basedirs Barcode1 --minimum-test-reads 1 --processes 8 --statistics-file-basename level_comp_stats --multiprocess-region-size 1000`
[12:30:54] Parsing Tombo index file(s).
[12:31:15] Performing two-sample group comparison significance testing.
[12:31:15] Parsing Tombo index file(s).
[12:31:36] Calculating read coverage regions.
[12:31:36] Calculating read coverage.
[12:31:43] Calculating read coverage.
[12:32:15] Performing modified base detection across genomic regions.
100%|████████████████████████████████████████████████████████████████████████████████████████| 337378/337378 [3:17:12<00:00, 28.51it/s]

Does increasing multiprocess-region-size account for such a dramatic performance difference in your opinion? Could my user-error of having minimum-test-reads set too high cause slow performance in any way? What does the output above where it says "337378/337378" mean, and does the increase of multiprocess-region-size explain these numbers compared to the prior higher value of "13494359/13494359" for the same data set? (reported "it/s" is similar for both runs, so it's this difference that seems to account for the dramatic performance improvement).

Note that nothing else runs on the CPU's on this server, but it does share storage over 10G network. I suppose disk competition could be an issue, but am surprised at the drastic performance change as this was pretty consistent over the 112 hours of last run, not just during peak times.

I was able to subsequently run `tombo plot` and also generate wig file this time (using the non-empty 2.3GB stats output file).

**Comment by marcus1487** [comment] 2020-03-10 01:43
The increase in multi process region size could indeed cause this large a decrease in run time especially given the network file system. Generally this value should be set as high as possible within ram limits. There may be some additional room to optimize the run time by increasing this value further. This indicates that extracting the levels from files is the limiting factor in processing and transferring files to faster disk access could drastically decrease run time. This is a design flaw in tombo, that unfortunately requires a large refactor to fix. 

The status updates are over regions to process. This is why the number decreases when this value is changed. 

I would suspect the you could probably filter many fewer reads and still process effectively. The coverage filter should generally be applied just to the point where the large peaks in coverage are removed (as these are what drastically increases ram usage). This should increase the power of the produced test statistics.

**Closed** 2020-03-16 15:40 UTC
