### ISSUE TITLE
All Reads Are Failing

### ISSUE THREAD

**Issue by alex-sal** [nanoporetech/tombo#43] opened 2018-03-22 03:24 UTC
Hi,

I am trying to use tombo to resquiggle a set of .fast5 reads but all of them are failing.
I have attempted to use different sets of .fast5 files with the same result. I tried to use unannotated .fast5 files after running the annotation command (annotate_raw_with_fastqs). I also attempted to use basecalled .fast5 files that did not have events called onto them; all with the same result. 
this is the error I am getting:
`tombo resquiggle ~/path/to/Fast5reads/Directory/1/  ~/path/to/Reference/Reference.fa --processes 8`
Loading minimap2 reference.
Getting file list.
Using default canonical ***** DNA ***** model.
Estimating global scale parameter
Correcting 4000 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).
...
Failed reads summary (4000 total failed):
	'AAAGG\r' :	25
	'ACCCA\r' :	1
	'ACCGC\r' :	2
	'ACGTC\r' :	3
	'ATCTC\r' :	2
	'ATGTC\r' :	205
	'CCCCG\r' :	1
	'CCCGG\r' :	4
	'CCGCC\r' :	104
	'CGTCC\r' :	2
	'CTCCT\r' :	4
	'CTCTC\r' :	192
	'CTGCG\r' :	4
	'CTTCT\r' :	5
	'C\rCCCG' :	1
	'GAGGA\r' :	3
	'GCCGC\r' :	14
	'GGACT\r' :	1
	'GGAGC\r' :	5
	'GGGGC\r' :	22
	'G\rAGAA' :	1
	'TCTC\rC' :	4
	'TCT\rGG' :	1
	'TC\rCGA' :	2
	'TGAAC\r' :	6
	'TGCGC\r' :	3
	'TTTTA\r' :	1
	'\rCCCGG' :	1
	'\rCCGGG' :	1
	'\rGCCCC' :	1
	Alignment not produced :	3123
	Discordant mapped position and sequence :	256

When I open the .fast5 the file has under Analysis it has a new field in it (RawGenomeCorrected_000) that is empty. I believe that is the field that should contain the resquiggled information. 
Thank You

**Comment by marcus1487** [comment] 2018-03-22 03:40
This looks like an issue with windows line feed characters. I can’t tell if this is an issue with the reference fasta file or the stored fastq read sequences. Were these reads processed with ‘annotate_raw_with_fastq’?

**Comment by alex-sal** [comment] 2018-03-22 03:49
Thank you for the response, no those reads where not processed with annotate_raw_with_fastq, they were obtained from MinIon basecaller. 

You state that it looks like an issue with the windows line feed characters, I am using Ubuntu 16.04 LTS, is this script suited to run on windows machines instead?

**Comment by marcus1487** [comment] 2018-03-22 04:05
No, tombo is not suited to run on windows. I have seen ‘\r’ characters in files processed or transferred from windows. That is the reason for thinking this might be a windows issue. 

My best guess is this is an error from processing the reference fasta file. Do you have the optional dependency pyfaidx installed?

**Comment by marcus1487** [comment] 2018-03-22 14:22
Looking at this a bit closer, it does appear at least to be an issue with the reference FASTA file. There are a number of reads failing with the error code `Discordant mapped position and sequence` indicating that the `mappy` mapped position and the length of the corresponding extracted sequence do not indicate the same information.

This may be an issue with the `pyfaidx` fasta index not recognizing the line feed characters. If you could try to run this command with and without `pyfaidx` installed that would help pinpoint the issue. 

Another thought is that this could have to do with how python2 reads line feeds. Are you using python2 or 3?

**Comment by alex-sal** [comment] 2018-03-22 14:28
Thank you for the reply, I am currently using python 3.5 to run this, I do not believe I have pyfaidx installed, I will install it and rerun the reads. Would you have any recommendation on what is the best way to create the fasta file? 

the '\r' character in the string started appearing after the 1.2.1 update. when I ran the data using 1.2 the string was displayed without the '\r'. I will rerun the data on a different server later today and see if I get any different results.

**Comment by marcus1487** [comment] 2018-03-22 14:50
Looking through the diff for version 1.2.1 one change I see that could be causing this was converting from using `pyfaidx`'s `Fasta` interface, to the `Faidx`interface, which was intended to provide faster on disk sequence access ([change here in the code](https://github.com/nanoporetech/tombo/commit/9ff653d60638f0e15f373b774b8eeded5ebacb52#diff-7ef45f6b9ad6e62f210628fbf8e828ddL214)). But if you do not have `pyfaidx` installed that would obviously not be causing this issue.

If you look at the file with the `less` command line tool, do you see `^M` characters in the middle of lines? As for how to create a fasta file, this is a bit open ended, but it really just comes down to not having the line feed characters in the file. That being said it would be nice to track this down so that `Tombo` can handle this situation.

One other idea would be to manually remove the line feeds from your reference. Could you try this command and then re-run your Tombo command with the converted reference: `cat ~/path/to/Reference/Reference.fa | tr -d "\r" > ~/path/to/Reference/Reference.no_line_feeds.fa`.

**Comment by alex-sal** [comment] 2018-03-26 03:53
Thank you for the recommendation to remove the "\r", the fasta file that I had was the issue. I did not consider this before as when I ran an alignment with BWA I did not get any errors regarding the Reference fasta file. Using the fasta file after running the command produces resqueggling results Thank You for all your help. I also update the pyfaidx to the latest version and now it seems that I can further proccess the data.

**Comment by marcus1487** [comment] 2018-03-26 14:40
I am glad you were able to resolve this issue!

The processing of the FASTA file is a bit different in Tombo (as compared to BWA) as I am currently accessing the sequence from both the `mappy` interface and the `pyfaidx` interface. This should be fixed in the next release when I can include [a fix for sequence extraction from `mappy`](https://github.com/lh3/minimap2/issues/126) that is being added to the next minimap2 release.

In order to make sure this issue does not pop up in other places around Tombo, would you mind confirming that updating `pyfaidx` alone fixes the issue (with the original fasta file containing `\r` characters)? If so do you happen to know the old and new versions you were using? This would help me to possibly put a minimal `pyfaidx` version dependency to avoid this issue. Thanks!

**Comment by alex-sal** [comment] 2018-03-29 22:58
Sorry it took me so long to reply, I think updating `pyfaidx` had no effect, however removing the `\r` from the reference solves the issue. 
I ran the sequence over a small sample I have to see if there is any difference in having the alignment sequence capitalized, lower case, or a mixture of the two. 
I expect most of the reads to fail in that file as they probably do not cover the region.
I tested the file with those parameters with different sequence capitalization
`tombo resquiggle ~/TestRawData/Directory/ ~/ReferenceDirectory/Reference.no_line_feeds.fa --dna --overwrite --processes 8`
Before removing the `\r` all reads failed 4000/4000

mixedCase after removing the `\r` command, 3132/4000 failed 
	Alignment not produced :	3123
	Poor raw to expected signal matching :	7
	Poor raw to expected signal matching at read start :	2

Reference Sequence in lower case after removing `\r` 3133/4000 failed 
	Alignment not produced :	3123
	Poor raw to expected signal matching :	8
	Poor raw to expected signal matching at read start :	2

Reference Sequence in Upper Case  after removing `\r` 3134/4000 failed
	Alignment not produced :	3123
	Not enough raw signal around potential genomic deletion(s) :	1
	Poor raw to expected signal matching :	8
	Poor raw to expected signal matching at read start :	2

The results sometimes varied by one read more or less, when I reran the test on the same set. That might be just the data I have. 
Thank You

**Closed** 2018-03-29 23:00 UTC
Labels: bug
