### ISSUE TITLE
preprocessing issues - warning for adding basecall information from Guppy

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/tombo#245] opened 2020-05-13 17:22 UTC
Hi Marcus,

I have 2 issues using the tombo, and would appreciate your help.

I had a mixture sample from different species(e.g. 50g DNA from E.coli and 350g DNA from human). I performed Nanopore sequencing on the mixture and run Guppy for basecalling on the multiple-read files. 
I want to use Tombo for chromosome separation because Tombo will perform a mapping of the fast5 entries with base calling information against the provided reference sequence database using minimap2. I think the mapping results are sufficient for one to separate by organism and chromosomes. So here is my idea:

Unzip original raw signal files `.fast5_pass.tar` to `.fast5` -> Convert multi-read file `.fast5` to single-read file with `ont_fast5_api` -> Add basecall information from a set of FASTQs to raw read files with `annotate_raw_with_fastq`  ->  Resquiggling by Tombo -> Add E.coli as "additional chromosome" to `human .fasta` to get a new `reference .fasta` -> Separation by chromosome by Tombo for per chromosome reads .fast5 by comparing with `reference .fasta`

1. Is it practical to use Tombo to do the chromosome separation as I described above?

2. When I tried the `annotate_raw_with_fastq`  step, I have the same issue with 
https://github.com/nanoporetech/tombo/issues/112, I also keep getting a warning and 0 adding sequences.

```
(myenv) [c-panz]$ tombo preprocess annotate_raw_with_fastqs --fast5-basedir Nanopore/test/single_reads/0 --fastq-filenames Nanopore/data/test1.fq --sequencing-summary-filenames Nanopore/5hmC/data/sequencing_summary.txt --processes 4
[12:54:33] Getting read filenames.
[12:54:33] Parsing sequencing summary files.
******************** WARNING ********************
	Some FASTQ records from sequencing summaries do not appear to have a matching file.
[12:54:33] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:00, ?it/s]
[12:54:34] Added sequences to a total of 0 reads.
```
`--fast5-basedir`: Nanopore/test/single_reads/0 contains single-read file after `ont_fast5_api` command
`--fastq-filenames`: Nanopore/data/test1.fq is the .fq with base calling information after `Guppy`. It should be multiple arguments.
`--sequencing-summary-filenames`: It is sequencing_summary.txt which I got after the sequencing and Guppy

I checked the single-read file name(e.g. `00076a41-8ae3-49e2-bd57-c767730222e6.fast5` and read_ids in the sequencing_summary.txt and found they are indeed corresponding. 
```
(base) [c-panz]$ grep -i "00076a41-8ae3-49e2-bd57-c767730222e6" sequencing_summary.txt
filename_fastq	filename_fast5	read_id	run_id	channel	mux	start_time	duration	num_events	passes_filtering	template_start	num_events_template	template_duration	sequence_length_template	mean_qscore_template	strand_score_template	median_template	mad_template
FAK62968_d91ad31c79c775c842fbd9190b78583d166c15a0_0.fastq	FAK62968_d91ad31c79c775c842fbd9190b78583d166c15a0_0.fast5	00076a41-8ae3-49e2-bd57-c767730222e6	d91ad31c79c775c842fbd9190b78583d166c15a0	104  	3	289.364250	1.968500	0	TRUE	289.436750	0	1.896000	609	10.655344	0.000000	97.864967	9.127304
```

In this case, do you have any suggestion to solve the `annotate_raw_with_fastq` problem?

Thank you so much for your help!

Best,
Ziwei

**Comment by marcus1487** [comment] 2020-05-13 17:42
I'm not sure if this is the issue, but it appears that the fast5 filenames listed in the sequencing summary file and those found in the `--fast5-basedir` location. This would point tombo to the wrong fast5 file and produce output such as this with `0` reads processed. This would also cause the warning concerning fastq records without matching file from the sequencing summary file. Since the `multi_to_single_fast5` program does not produce a sequencing summary file it would be best to drop the sequencing summary file from the command and try this again.

**Comment by PanZiwei** [comment] 2020-05-13 18:47
> I'm not sure if this is the issue, but it appears that the fast5 filenames listed in the sequencing summary file and those found in the `--fast5-basedir` location. This would point tombo to the wrong fast5 file and produce output such as this with `0` reads processed. This would also cause the warning concerning fastq records without matching file from the sequencing summary file. Since the `multi_to_single_fast5` program does not produce a sequencing summary file it would be best to drop the sequencing summary file from the command and try this again.

Hi I retried again with the command and it still has the same issue:
```
(myenv) [c-panz]$ tombo preprocess annotate_raw_with_fastqs --fast5-basedir Nanopore/test/single_reads/0 --fastq-filenames Nanopore/data/test1.fq --processes 4
[14:43:31] Preparing reads and extracting read identifiers.
/Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
****** WARNING ****** Basecalls exsit in specified slot for some reads. Set --overwrite option to overwrite these basecalls.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4000/4000 [00:12<00:00, 310.91it/s]
[14:43:46] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:00, ?it/s]
[14:43:46] Added sequences to a total of 0 reads.
```

I think fast5 filenames listed in the sequencing summary file are actually multi-read files, but the fast5 in the `--fast5-basedir` location is single-read files generated by `ont_fast5_api`. For example, a fast5 in the summary file should contain multiple fast5 in the `--fast5-basedir` location and the latter one should be distinguished by read_id since read_id is a unique number.

**Comment by marcus1487** [comment] 2020-05-13 18:52
It does seem that the sequencing summary file lists the multi-fast5 filenames. And this seems to have fixed the first issue.

This new output is actually quite different from the previous output. Note the new warning indicates that the basecall slot is already written and that the `--overwrite` flag is not set. Setting the `--overwrite` flag should resolve this issue. Note though that this likely means the basecalls are already there, though to be sure the same basecalls from the fastqs are loaded into the fast5s it is a good idea to perform this step still.

**Comment by PanZiwei** [comment] 2020-05-13 19:01
I added the `--overwrite` flag and it seems worked! 

Just one more question: 
**How can I check whether I successfully add the right baseball information from Guppy to raw read files? Can I keep both the original and the annotation one instead of directly overwriting it?**


Here is the result:
```
(myenv) [c-panz]$ tombo preprocess annotate_raw_with_fastqs --fast5-basedir /Nanopore/test/single_reads/0 --fastq-filenames /Nanopore/data/test1.fq --overwrite --processes 4
[14:54:11] Preparing reads and extracting read identifiers.
/Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4000/4000 [00:11<00:00, 335.76it/s]
[14:54:23] Annotating FAST5s with sequence from FASTQs.
 62%|█████████████████████████████████████████████████████████████████████████▏                                           | 2500/4000 [00:04<00:02, 565.73it/s]
[14:54:28] Added sequences to a total of 2500 reads.
******************** WARNING ********************
	Not all read ids from FAST5s or sequencing summary files were found in FASTQs.
		This can result from reads that failed basecalling or if full sets of FAST5s/sequence summaries are not processed with full sets of FASTQs.
```

Thank you so much for the help!

**Comment by marcus1487** [comment] 2020-05-13 20:59
I'm not sure what you mean by "check whether I successfully add the right baseball information from Guppy to raw read files". Could you explain what you are after here? Tombo will add all basecalls from the provided fastqs to annotate all reads in the fast5s provided where the read_id matches. If you don't see the total number of reads annotated in the output that you expect then the most likely reason is that the reads are not from the same complete sets.

For the idea to retain the original read file, yes this is recommended. The choice to have Tombo write back to the fast5 files was a poor design choice. This workflow can cause some files to be corrupted, so it is recommended to save the original read files. Unfortunately the fix for this issue will take a large amount of work to correct and likely will not be completed in this form of the Tombo code base.

**Comment by marcus1487** [comment] 2020-05-13 21:00
To clarify you should still have the basecalls stored in the multi-fast5 format files, so saving the basecalls in the single fast5 format is likely not necessary.

**Comment by PanZiwei** [comment] 2020-05-19 03:27
> To clarify you should still have the basecalls stored in the multi-fast5 format files, so saving the basecalls in the single fast5 format is likely not necessary.

Hi, when I tried `tombo resquiggle` with the following command:

```
tombo resquiggle --dna --processes 4 --corrected-group RawGenomeCorrected_000 --basecall-group Basecall_1D_000 --basecall-subgroups BaseCalled_template --overwrite Nanopore/test/data/fast5/ reference.fasta  
```

I got the error: 
```
[22:50:00] Loading minimap2 reference.
[22:53:43] Getting file list.
******************** ERROR ********************
Reads do not to contain basecalls. Check --basecall-group option if basecalls are stored in non-standard location or use `tombo preprocess annotate_raw_with_fastqs` to add basecalls from FASTQ files to raw FAST5 files.
```

However, in the previous `tombo preprocess annotate_raw_with_fastqs` step, when I use command `tombo preprocess annotate_raw_with_fastqs --fast5-basedir /Nanopore/test/single_reads/0 --fastq-filenames /Nanopore/data/test.fq --processes 4 --overwrite`, it shows that "Added sequences to a total of 152941 reads." so I believe that  **I successfully add basecalls from a set of FASTQs to raw read files.**

Here are the results after  `tombo preprocess annotate_raw_with_fastqs` command:

```
Preparing reads and extracting read identifiers.

  0%|          | 0/152941 [00:00<?, ?it/s]
  0%|          | 100/152941 [00:01<33:28, 76.08it/s]
  0%|          | 400/152941 [00:01<10:16, 247.26it/s]
  0%|          | 700/152941 [00:02<08:47, 288.39it/s]
  1%|          | 1000/152941 [00:03<08:57, 282.57it/s]
.....
100%|█████████▉| 152800/152941 [14:13<00:00, 179.06it/s]/Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
Anaconda3/envs/myenv/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
100%|██████████| 152941/152941 [14:13<00:00, 179.18it/s]
[23:32:29] Annotating FAST5s with sequence from FASTQs.
  0%|          | 0/152941 [00:00<?, ?it/s]
  0%|          | 100/152941 [00:00<23:00, 110.74it/s]
  0%|          | 500/152941 [00:01<08:39, 293.22it/s]
  1%|          | 900/152941 [00:02<07:20, 345.19it/s]
.....
100%|██████████| 152941/152941 [06:06<00:00, 417.71it/s]
[23:38:35] Added sequences to a total of 152941 reads.
```

In this case, do you have an idea about the failure reason for the `tombo resquiggle`  step?

**Comment by PanZiwei** [comment] 2020-05-19 13:30
> To clarify you should still have the basecalls stored in the multi-fast5 format files, so saving the basecalls in the single fast5 format is likely not necessary.

Hi Marcus, 

I tried to use `tombo resquiggle` step but it is still under process and it is **very slow**. Here is the command I am using: 
```
tombo resquiggle --dna --processes 4 --corrected-group RawGenomeCorrected_000 --basecall-group Basecall_1D_000 --basecall-subgroups BaseCalled_template --overwrite Nanopore/test/single_reads/0 reference.fa --ignore-read-locks
```

Here is the processing log results:
```
[08:48:00] Loading minimap2 reference.
[08:51:09] Getting file list.
[08:52:08] Re-squiggling reads (raw signal to genomic sequence alignment).

  0%|                                                                                            | 0/152941 [00:00<?, ?it/s]
  0%|                                                                                  | 5/152941 [00:01<8:30:33,  4.99it/s]
  0%|                                                                                | 10/152941 [00:04<17:00:44,  2.50it/s]
  0%|                                                                                | 18/152941 [00:07<16:32:58,  2.57it/s]
  0%|                                                                                | 27/152941 [00:10<15:45:29,  2.70it/s]
  0%|                                                                                | 36/152941 [00:16<18:54:39,  2.25it/s]
  0%|                                                                                | 45/152941 [00:20<18:54:38,  2.25it/s]
  0%|                                                                                | 55/152941 [00:27<20:52:56,  2.03it/s]
```

It is only ~1.5-2it/s, which is very slow....Do you have any idea about this issue? 

Also, even after the `resquiggle` step they are still single-read files, how can I know the organism of single-read or do the separation based on chromosomes since my sequencing sample is a mixture of human and E.coli?

**Comment by marcus1487** [comment] 2020-05-27 17:09
Are you setting the `--processes` value to an appropriate value for your compute capacity? Are the tombo processes using the number of processes requested? Alternatively, very slow processing is often caused by data stored on a slower disk. Are your FAST5 files stored over an NFS? Storing reads on a local fast (e.g. SSD) disk can often drastically increase speed. 

If you are very interested in figuring out what is slowing processing you can clone the repository from github, edit [this value](https://github.com/nanoporetech/tombo/blob/master/tombo/resquiggle.py#L72) to `True`. This will produce the `resquiggle_main.prof` file which can be inspected with [the `pyprof2calltree` package](https://pypi.org/project/pyprof2calltree/) (e.g. `pyprof2calltree -i resquiggle_main.prof -k`. 

The mapped reference chromosome would likely be the best indicator of the organism of origin for a read (pedantic caveat: there are any many exceptions to this rule; especially if a read's true source is not represented in the reference sequences).

**Closed** 2020-06-03 02:44 UTC
Labels: question

**Comment by YantingHuang** [comment] 2021-09-01 04:23
> Hi Marcus,
> 
> I have 2 issues using the tombo, and would appreciate your help.
> 
> I had a mixture sample from different species(e.g. 50g DNA from E.coli and 350g DNA from human). I performed Nanopore sequencing on the mixture and run Guppy for basecalling on the multiple-read files.
> I want to use Tombo for chromosome separation because Tombo will perform a mapping of the fast5 entries with base calling information against the provided reference sequence database using minimap2. I think the mapping results are sufficient for one to separate by organism and chromosomes. So here is my idea:
> 
> Unzip original raw signal files `.fast5_pass.tar` to `.fast5` -> Convert multi-read file `.fast5` to single-read file with `ont_fast5_api` -> Add basecall information from a set of FASTQs to raw read files with `annotate_raw_with_fastq` ->  Resquiggling by Tombo -> Add E.coli as "additional chromosome" to `human .fasta` to get a new `reference .fasta` -> Separation by chromosome by Tombo for per chromosome reads .fast5 by comparing with `reference .fasta`
> 
> 1. Is it practical to use Tombo to do the chromosome separation as I described above?
> 2. When I tried the `annotate_raw_with_fastq`  step, I have the same issue with
>    [preprocessing issues - warning and multiple fast5 & fastq files #112](https://github.com/nanoporetech/tombo/issues/112), I also keep getting a warning and 0 adding sequences.
> 
> ```
> (myenv) [c-panz]$ tombo preprocess annotate_raw_with_fastqs --fast5-basedir Nanopore/test/single_reads/0 --fastq-filenames Nanopore/data/test1.fq --sequencing-summary-filenames Nanopore/5hmC/data/sequencing_summary.txt --processes 4
> [12:54:33] Getting read filenames.
> [12:54:33] Parsing sequencing summary files.
> ******************** WARNING ********************
> 	Some FASTQ records from sequencing summaries do not appear to have a matching file.
> [12:54:33] Annotating FAST5s with sequence from FASTQs.
> ****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
> 0it [00:00, ?it/s]
> [12:54:34] Added sequences to a total of 0 reads.
> ```
> 
> `--fast5-basedir`: Nanopore/test/single_reads/0 contains single-read file after `ont_fast5_api` command
> `--fastq-filenames`: Nanopore/data/test1.fq is the .fq with base calling information after `Guppy`. It should be multiple arguments.
> `--sequencing-summary-filenames`: It is sequencing_summary.txt which I got after the sequencing and Guppy
> 
> I checked the single-read file name(e.g. `00076a41-8ae3-49e2-bd57-c767730222e6.fast5` and read_ids in the sequencing_summary.txt and found they are indeed corresponding.
> 
> ```
> (base) [c-panz]$ grep -i "00076a41-8ae3-49e2-bd57-c767730222e6" sequencing_summary.txt
> filename_fastq	filename_fast5	read_id	run_id	channel	mux	start_time	duration	num_events	passes_filtering	template_start	num_events_template	template_duration	sequence_length_template	mean_qscore_template	strand_score_template	median_template	mad_template
> FAK62968_d91ad31c79c775c842fbd9190b78583d166c15a0_0.fastq	FAK62968_d91ad31c79c775c842fbd9190b78583d166c15a0_0.fast5	00076a41-8ae3-49e2-bd57-c767730222e6	d91ad31c79c775c842fbd9190b78583d166c15a0	104  	3	289.364250	1.968500	0	TRUE	289.436750	0	1.896000	609	10.655344	0.000000	97.864967	9.127304
> ```
> 
> In this case, do you have any suggestion to solve the `annotate_raw_with_fastq` problem?
> 
> Thank you so much for your help!
> 
> Best,
> Ziwei

Hi Ziwei,

If I have fast5 file, which contains multiple reads data, do I need to split all it into multiple fast5 files and each of them only contains a single read?

Best,
Yanting

**Comment by PanZiwei** [comment] 2021-09-01 04:38
@YantingHuang 
You can use [ont_fast5_api](https://github.com/nanoporetech/ont_fast5_api) toconvert between multi_read and single_read formats.
