### ISSUE TITLE
 strongly recommend tombo can support multi-fast5

### ISSUE THREAD

**Issue by hygine** [nanoporetech/tombo#230] opened 2020-03-14 09:46 UTC
It is strongly recommended that tombo software can support multiple fast5 files. It takes a long time to transfer these fast5 files when our data volume is extremely large, and the transfer is also affected by the maximum IO level of the HPC, which greatly affects the analysis efficiency.
I strongly hope that you can adopt our opinions. Now all the sequencing data are combined by multi-fast5, unlike ONT sequencing at the beginning. The original analysis model is no longer suitable for analyzing the current data.
Thank you.
@marcus1487

**Comment by marcus1487** [comment] 2020-03-24 13:36
This is a duplicate of #87 . This is certainly under consideration, though the development time to convert the whole code base over to a new intermediate data processing structure while maintaining the current capabilities is quite significant. At this time there is no time table to complete this task, but this pain point is duly noted.

**Closed by marcus1487** 2020-03-24 13:36 UTC
Labels: duplicate, enhancement
